// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoovys6DZ62cO27iLpIev1FUu6RT_LMgs',
    appId: '1:302101047993:web:832fc50dc987035d628968',
    messagingSenderId: '302101047993',
    projectId: 'graduation-project-e8a09',
    authDomain: 'graduation-project-e8a09.firebaseapp.com',
    storageBucket: 'graduation-project-e8a09.appspot.com',
    measurementId: 'G-N384CMPZS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJhbMyjCUSNUuRfSu7N3AiZn_dxcge0A',
    appId: '1:302101047993:android:0ee1576061177d12628968',
    messagingSenderId: '302101047993',
    projectId: 'graduation-project-e8a09',
    storageBucket: 'graduation-project-e8a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwg4cheAIcWiyvAfh7_BsqHjvS44VWx0I',
    appId: '1:302101047993:ios:9b0977971f366bd5628968',
    messagingSenderId: '302101047993',
    projectId: 'graduation-project-e8a09',
    storageBucket: 'graduation-project-e8a09.appspot.com',
    iosBundleId: 'com.example.gradutionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwg4cheAIcWiyvAfh7_BsqHjvS44VWx0I',
    appId: '1:302101047993:ios:10f49a505eb369c1628968',
    messagingSenderId: '302101047993',
    projectId: 'graduation-project-e8a09',
    storageBucket: 'graduation-project-e8a09.appspot.com',
    iosBundleId: 'com.example.gradutionProject.RunnerTests',
  );
}
